import { CrewMember, ShiftConfig } from './types';

export const mockCrewMembers: CrewMember[] = [
  {
    id: 'crew-1',
    name: 'Maria Lopez',
    nickname: 'Mari',
    position: 'Chief Stewardess',
    department: 'Interior',
    color: '#C8A96B', // Gold
    avatar: 'https://images.unsplash.com/photo-1581065178026-390bc4e78dad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc1OTk4NTI5Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'maria.lopez@yacht.com',
    phone: '+1 555 0101',
    onBoardContact: 'Ext. 201',
    status: 'off-duty',
    languages: ['English', 'Spanish', 'French'],
    skills: ['Wine Service', 'Table Setting', 'Guest Relations'],
  },
  {
    id: 'crew-2',
    name: 'Sarah Johnson',
    position: 'Second Stewardess',
    department: 'Interior',
    color: '#D4A5A5', // Rose
    avatar: 'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzc3dvbWFuJTIwaGVhZHNob3R8ZW58MXx8fHwxNzU5OTE2ODg5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'sarah.johnson@yacht.com',
    phone: '+1 555 0102',
    onBoardContact: 'Ext. 202',
    status: 'off-duty',
    languages: ['English', 'Italian'],
    skills: ['Housekeeping', 'Laundry', 'Guest Service'],
  },
  {
    id: 'crew-3',
    name: 'Sophie Martin',
    position: 'Stewardess',
    department: 'Interior',
    color: '#C8B4A6', // Taupe
    avatar: 'https://images.unsplash.com/photo-1655249481446-25d575f1c054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBoZWFkc2hvdCUyMHdvbWFufGVufDF8fHx8MTc1OTkzNTM3MXww&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'sophie.martin@yacht.com',
    phone: '+1 555 0103',
    onBoardContact: 'Ext. 203',
    status: 'off-duty',
    languages: ['English', 'French'],
    skills: ['Silver Service', 'Floral Arrangements'],
  },
  {
    id: 'crew-4',
    name: 'Emma Wilson',
    nickname: 'Em',
    position: 'Stewardess',
    department: 'Interior',
    color: '#D4C5A9', // Beige
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHByb2Zlc3Npb25hbCUyMHdvbWFufGVufDF8fHx8MTc1OTk5MzI1OXww&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'emma.wilson@yacht.com',
    phone: '+1 555 0104',
    onBoardContact: 'Ext. 204',
    status: 'off-duty',
    languages: ['English', 'German'],
    skills: ['Mixology', 'Event Planning'],
  },
  {
    id: 'crew-5',
    name: 'Olivia Taylor',
    nickname: 'Liv',
    position: 'Junior Stewardess',
    department: 'Interior',
    color: '#D4B08C', // Warm Sand
    avatar: 'https://images.unsplash.com/photo-1641808895769-29e63aa2f066?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMGJ1c2luZXNzd29tYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjAwMDY3NDJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'olivia.taylor@yacht.com',
    phone: '+1 555 0105',
    onBoardContact: 'Ext. 205',
    status: 'off-duty',
    languages: ['English'],
    skills: ['Cabin Service', 'Photography'],
  },
  {
    id: 'crew-6',
    name: 'David Brown',
    nickname: 'Dave',
    position: 'Chef de Cuisine',
    department: 'Interior',
    color: '#9FBEAA', // Sage
    avatar: 'https://images.unsplash.com/photo-1678626667639-de9c676e8222?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGVmJTIwcHJvZmVzc2lvbmFsJTIwcG9ydHJhaXR8ZW58MXx8fHwxNzYwMDA2NzM5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'david.brown@yacht.com',
    phone: '+1 555 0106',
    onBoardContact: 'Ext. 401',
    status: 'off-duty',
    languages: ['English', 'French', 'Spanish'],
    skills: ['Fine Dining', 'Pastry', 'Menu Planning', 'Allergen Management'],
  },
  {
    id: 'crew-7',
    name: 'Isabella Rodriguez',
    nickname: 'Bella',
    position: 'Sous Chef',
    department: 'Interior',
    color: '#B5A89F', // Warm Gray
    avatar: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMGNoZWYlMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjAwMDY3NDJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'isabella.rodriguez@yacht.com',
    phone: '+1 555 0107',
    onBoardContact: 'Ext. 402',
    status: 'off-duty',
    languages: ['English', 'Spanish', 'Italian'],
    skills: ['Mediterranean Cuisine', 'Plating', 'Dietary Requirements'],
  },
  {
    id: 'crew-8',
    name: 'Charlotte Davies',
    nickname: 'Charlie',
    position: 'Junior Stewardess',
    department: 'Interior',
    color: '#C5A8B4', // Dusty Rose
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHByb2Zlc3Npb25hbCUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MXx8fHwxNzYwMDA2NzQzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'charlotte.davies@yacht.com',
    phone: '+1 555 0108',
    onBoardContact: 'Ext. 206',
    status: 'off-duty',
    languages: ['English'],
    skills: ['Turndown Service', 'Ironing'],
  },
  {
    id: 'crew-9',
    name: 'Amelia Thompson',
    nickname: 'Amy',
    position: 'Stewardess',
    department: 'Interior',
    color: '#A8C5C4', // Seafoam
    avatar: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2MDAwNjc0M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'amelia.thompson@yacht.com',
    phone: '+1 555 0109',
    onBoardContact: 'Ext. 207',
    status: 'off-duty',
    languages: ['English', 'Portuguese'],
    skills: ['Guest Relations', 'Event Coordination'],
  },
  {
    id: 'crew-10',
    name: 'Grace Williams',
    position: 'Junior Stewardess',
    department: 'Interior',
    color: '#D4C4A8', // Champagne
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMHByb2Zlc3Npb25hbCUyMHBvcnRyYWl0fGVufDF8fHx8MTc2MDAwNjc0M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    email: 'grace.williams@yacht.com',
    phone: '+1 555 0110',
    onBoardContact: 'Ext. 208',
    status: 'off-duty',
    languages: ['English', 'French'],
    skills: ['Cocktail Service', 'Table Arrangements'],
  },
];

export const defaultShiftConfig: ShiftConfig[] = [
  {
    id: 'morning',
    name: 'Morning',
    startTime: '06:00',
    endTime: '14:00',
    primaryCount: 2,
    backupCount: 1,
    color: '#D4B877', // Gold - Morning shift
  },
  {
    id: 'afternoon',
    name: 'Afternoon',
    startTime: '14:00',
    endTime: '22:00',
    primaryCount: 2,
    backupCount: 1,
    color: '#06B6D4', // Cyan - Afternoon shift
  },
  {
    id: 'night',
    name: 'Night',
    startTime: '22:00',
    endTime: '06:00',
    primaryCount: 1,
    backupCount: 1,
    color: '#7C3AED', // Purple - Night shift
  },
];
